import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Hero from 'components/Hero'
import Navbar from 'components/Navbar'

const inter = Inter({ subsets: ['greek'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Captur photography" message="I capture moments on nature and keep them alive"/>
      <Navbar/>
    </>
  )
}
